name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest Build
          body: Automatically published build for commit ${{ github.sha }}
          artifacts: app/build/outputs/apk/debug/app-debug.apk
